#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl8,  metal,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  wood,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, plastic,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, clear,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, nothing,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

char marbleQueue[3] =
{
	"n",
	"n",
	"n"
};

bool checkAround(int value,int goal) {
	if (value > 1000) {
		if (goal - 120 < value && value < goal + 120) {
			return true;
			} else {
			return false;
		}
		} else {
		if (goal - 15 < value && value < goal + 15) {
			return true;
			} else {
			return false;
		}
	}
}

task main()
{
	turnLEDOff(nothing);
	turnLEDOff(clear);
	turnLEDOff(plastic);
	turnLEDOff(wood);
	turnLEDOff(metal);
	while(true) {
		turnFlashlightOn(Flashlight);
		if(SensorValue(lightSensor) > 30 || SensorValue(lineFollower) < 2960) {
			if(checkAround(SensorValue(lightSensor), 55) && checkAround(SensorValue(lineFollower), 2660)){
				writeDebugStreamLine("none"); // works
				turnLEDOn(nothing);
				turnLEDOff(clear);
				turnLEDOff(plastic);
				turnLEDOff(wood);
				turnLEDOff(metal);
			}
			if(checkAround(SensorValue(lightSensor), 20) && checkAround(SensorValue(lineFollower), 2890)) {
				writeDebugStreamLine("clear"); //works
				turnLEDOff(nothing);
				turnLEDOn(clear);
				turnLEDOff(plastic);
				turnLEDOff(wood);
				turnLEDOff(metal);
			}
			if(checkAround(SensorValue(lightSensor), 210) && checkAround(SensorValue(lineFollower), 300)) {
				writeDebugStreamLine("plastic"); //works
				turnLEDOff(nothing);
				turnLEDOff(clear);
				turnLEDOn(plastic);
				turnLEDOff(wood);
				turnLEDOff(metal);
			}
			if(checkAround(SensorValue(lightSensor), 325) && checkAround(SensorValue(lineFollower), 1410)) {
				writeDebugStreamLine("wood"); //works
				turnLEDOff(nothing);
				turnLEDOff(clear);
				turnLEDOff(plastic);
				turnLEDOn(wood);
				turnLEDOff(metal);
			}
			if(checkAround(SensorValue(lightSensor), 315) && checkAround(SensorValue(lineFollower), 2950)) {
				writeDebugStreamLine("metal"); //works
				turnLEDOff(nothing);
				turnLEDOff(clear);
				turnLEDOff(plastic);
				turnLEDOff(wood);
				turnLEDOn(metal);
			}
			} else {
			writeDebugStreamLine("nothing");
		}
	}
}
